-- Auto-generated by scripts/build-changes-seed.js — seeds the Recent Changes feed.
-- Import with:  wrangler d1 execute d1-template-database --remote --file=scripts/seed-recent-changes.sql
-- (or paste into the D1 Console). Replaces every row in recent_changes.
-- No BEGIN/COMMIT: D1 forbids SQL transaction statements and runs a --file batch atomically.

CREATE TABLE IF NOT EXISTS recent_changes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,
    change TEXT NOT NULL,
    sort_order INTEGER
);

DELETE FROM recent_changes;
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 18, 2026', '**Glass Chapel** has been moved up from #129 to #78, below **Misanthrope** and above **Tight Clubstep**', 0);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 18, 2026', '**BALLISTIC BALLPIT** has been placed at #415, above **Erosion** and below **Between Duality**', 1);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 16, 2026', '**Angelicide** has been moved down from #9 to #17, above **TRUE METAL CRUSHER** and below **KOCMOC UNLEASHED**', 2);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 16, 2026', '**Heliopolis** has been moved down from #18 to #20, above **STEAM CRASHED UH OH** and below **Nebulabrasque**', 3);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 16, 2026', '**Vehemence** has been moved up from #23 to #16, above **KOCMOC UNLEASHED** and below **ReFRACTURED**', 4);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 14, 2026', '**Woofel** has been placed at #131, above **Every end** and below **Penumbral**', 5);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 14, 2026', '**Astaroth** has been placed at #207, above **Argentysm** and below **Kyouki**', 6);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 14, 2026', '**Phantasm IV** has been placed at #279, above **Firework** and below **Through The Gates**', 7);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 14, 2026', '**Fiberglass** has been placed at #359, above **The Only Wish** and below **The Yangire**', 8);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 13, 2026', '**Enchanting Skylight** has been placed at #387, above **Hitorigoto** and below **Sanguine**', 9);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 13, 2026', '**Africa Circles** has been placed at #89, above **Theory of Sevvend** and below **SILENT OPPENHEIMER**', 10);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 13, 2026', '**Theory of Sevvend** has been placed at #90, above **Tidal Wave** and below **Africa Circles**', 11);
INSERT INTO recent_changes (date, change, sort_order) VALUES ('April 13, 2026', '**NOTARTARUS** has been placed at #396, above **Waterfall** and below **IKEA LEVEL**', 12);

